site_name: Arista Newsletter

site_url: https://AristaUpstateNY.github.io/Newsletter/
repo_name: AristaUpstateNY/Newsletter
docs_dir: docs/
edit_uri: edit/main/docs/

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all

theme:
  name: material
  icon:
    admonition:
      quote: octicons/quote-16
      note: octicons/tag-16
  palette:
    primary: custom
  logo: 
  favicon: img/arista_logo.png

nav:
  - www.arista.com: http://www.arista.com
  - July 2025: index.md
  - June 2025: June2025.md
  - May 2025: May2025.md

extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright © 2025 Arista Networks. You are receiving this newsletter as a customer of Arista. 
  To stop receiving newsletters please contact Jeramiah Pauly - jpauly@arista.com
